### ISSUE TITLE
Vaadin 24?

### ISSUE THREAD

**Issue by flozano** [gl0b3/materialicons-flow#6]
Hi, 

Thanks for your project. Is there any chance to update it to work on vaadin 24?

Just by having its dependency in the classpath:

```groovy
    implementation "org.vaadin.addons.gl0b3:materialicons-flow:2.0.0"
```

renders the webapp unusable under vaadin flow 24.4.4

**Comment by gl0b3** [comment]
Hello!  I'm currently on vacation, but I'll see if the request can be resolved as soon as I return (next week).

**Comment by gl0b3** [comment]
The version 3.0.0 (Vaadin 24.4 compatible version - I tested with Vaadin 24.4.1) has uploaded to the Github. Tomorrow I'm gona upload to the Vaadin Directory...
Update: waiting for Vaadin Directory to upload the artifact into Maven Central Repository
Update 2: something stucked in the Vaadin Directory and I made some small fix in Jetty run, so I uploaded the 3.0.1 version. [https://vaadin.com/directory/component/material-icons-for-vaadin-14](https://vaadin.com/directory/component/material-icons-for-vaadin-14)
@flozano please take a look, thanks!

**Comment by flozano** [comment]
hey thanks a lot for this! I will check it when I'm back from vacation :) but in any case thank you.

**Comment by flozano** [comment]
Thank you, I confirmed it works well with latest vaadin 24.

**Comment by gl0b3** [comment]
You're welcome, thanks for testing :)
